config/routes.rb
Rails.application.routes.draw do

  root 'flights#index'
  resources :flights,  only:  :index
  resources :bookings,  only:  [:new, :create, :show]
end

app/models/airport.rb
class Airport < ActiveRecord::Base
  has_many :departing_flights, class_name: "Flight", foreign_key: "departure_airport_id"
  has_many :arriving_flights, class_name: "Flight", foreign_key: "arrival_airport_id"
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :flight
  has_many :passenger_bookings
  has_many :passengers, through: :passenger_bookings
  accepts_nested_attributes_for :passengers
  @@counter = 0

  def get_flight 
    Flight.find(self.flight_id)
  end

  def set_ref_number
    ref_number = "#{self.flight.id}-#{self.flight.from_airport.code}-#{self.flight.to_airport.code}-#{@@counter}"

    @@counter+=1
    self.update_attribute(:number, ref_number)
  end
end

app/models/flight.rb
class Flight < ActiveRecord::Base
  belongs_to :from_airport, class_name: "Airport", foreign_key: "departure_airport_id"
  belongs_to :to_airport, class_name: "Airport", foreign_key: "arrival_airport_id"

  has_many :bookings
  has_many :passengers, through: :bookings

  def self.date_list
    dates = Flight.all.order(departure_date: :asc)
    dates.map{|f| [f.departure_date.strftime("%d/%m/%Y") ]}.uniq
  end

  def self.search (departure, arrival, date)
    Flight.where(departure_airport_id: departure,
      arrival_airport_id: arrival,
      departure_date: Flight.correct_date(date))
  end
  
  def self.correct_date(date)
    unless date.nil?
      date = date.to_date
      date.beginning_of_day..date.end_of_day
    end
  end 
end

app/models/passenger.rb
class Passenger < ActiveRecord::Base
  has_many :passenger_bookings
  has_many :bookings, through: :passenger_bookings
  has_many :flights, through: :bookings

end

app/models/passenger_booking.rb
class PassengerBooking < ActiveRecord::Base
  belongs_to :booking
  belongs_to :passenger
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @flight = Flight.find(params[:flight_id])
    @passengers = params[:passengers]
    @booking = Booking.new
    @passengers.to_i.times { @booking.passengers.build }
  end

  def create
    @booking = Booking.new(booking_params)

    if @booking.save
      @booking.update_attribute(:flight_id, params[:flight_id])
      @booking.set_ref_number
      mail_users(@booking)
      flash[:success] = "trip booked"
      redirect_to booking_path(@booking)
    else
      @flight  = Flight.find(params[:flight_id])
      render 'new'
    end

  end

  def show
    @booking = Booking.find(params[:id])
  end

  private
    def booking_params
      params.require(:booking).permit(passengers_attributes: [:name, :email])
    end

    def mail_users (booking)
      booking.passengers.each do |p|
        PassengerMailer.welcome_email(p).deliver_now
      end
    end

end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController

  def index
    @departure_options = Airport.all.map{|u| [u.code, u.id]}
    @arrival_options = Airport.all.map{|u| [u.code, u.id]}
    @date_options = Flight.date_list

    @departure = params[:departure]
    @arrival = params[:arrival]
    @passengers = params[:passengers]
    @date = params[:date]

    @flights = Flight.search(@departure, @arrival, @date)


  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<h1>Booking</h1>

<%= label_tag(:departure_airport_id, "Departure Airport:") %>
<%= @flight.from_airport.code %> <br>

<%= label_tag(:arrival_airport_id, "Arrival Airport:") %>
<%= @flight.to_airport.code %><br>

<%= label_tag(:departure_date, "Departure date:") %>
<%= @flight.departure_date %><br>

<%= label_tag(:passengers, "Number of passengers:") %>
<%= @passengers %><br>

<%= label_tag(:flight_id, "Flight id:") %>
<%= @flight.id %><br>



<%= form_for @booking  do |f| %>
 
    <%= f.fields_for :passengers do |p| %>
    <h3>Passenger </h3>
      <p> Name </p>
      <%= p.text_field :name %>
      <p> Email </p>
      <%= p.text_field :email %>
    <% end %>

  <%= hidden_field_tag(:passengers, @passengers) %>

  <%= hidden_field_tag(:flight_id, @flight.id) %>

  <%= f.submit "Continue" %><br>
<% end %>

app/views/bookings/show.html.erb
<h2>Trip booked</h2>
<h2>Booking information</h2>
Booking ID: <%= @booking.id %> <br>
Flight ID: <%= @booking.get_flight.id %><br> 
Departure: <%= @booking.get_flight.from_airport.code %><br> 
Arrival: <%= @booking.get_flight.to_airport.code %><br> 
Date: <%= @booking.get_flight.departure_date %><br> 

<h2>Passengers</h2>
<ul>
  <% @booking.passengers.each do |passenger| %>
  <li><%= passenger.name %></li>
  <% end %>
</ul>

app/views/flights/index.html.erb
<h1>Search Flight</h1>

<%= form_tag(root_path, method: "get") do %>
  <%= label_tag(:departure_airport_id, "Departure Airport:") %>
  <%= select_tag(:departure, options_for_select(@departure_options)) %><br><br>

  <%= label_tag(:arrival_airport_id, "Arrival Airport:") %>
  <%= select_tag(:arrival, options_for_select(@departure_options)) %><br><br>

  <%= label_tag(:passengers, "Number of passengers:") %>
  <%= select_tag(:passengers, options_for_select([1,2,3,4])) %><br><br>

  <%= label_tag(:date, "Date:") %>
  <%= select_tag(:date, options_for_select(@date_options)) %><br><br>

  <%= submit_tag "Search", class: "btn btn-primary col-md-4 col-md-offset-8" %><br>
<% end %>



<% if !@flights.empty? %>
  <%= form_tag(new_booking_path, method: "get") do %>
    <% @flights.each do |f| %>
      <%= radio_button_tag(:flight_id, f.id) %>
      From <%= f.from_airport.code %>
      to <%= f.to_airport.code %>
      | Date <%= f.departure_date %>
      </p>
    <% end %>
    <%= hidden_field_tag(:passengers, params[:passengers]) %>
    <p><%= submit_tag "Select", class: "btn btn-primary col-md-4 col-md-offset-8" %></p>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OdinFlightBooker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<%= debug(params) if Rails.env.development? %>
</body>
</html>